# Dockerfile.server
FROM node:22-alpine
WORKDIR /app
COPY ./backend/package*.json ./
RUN npm install axios
RUN npm install
COPY ./backend .
RUN npm run build
CMD ["npm", "run", "start:prod"]
EXPOSE 5000
